# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160823173927 on 2016-08-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlefromweb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlefromweb',
            options={'ordering': ['-date_publish'], 'verbose_name': '\u7f51\u7edc\u6587\u7ae0', 'verbose_name_plural': '\u7f51\u7edc\u6587\u7ae0'},
        ),
        migrations.AlterField(
            model_name='articlefromweb',
            name='url',
            field=models.CharField(max_length=100, verbose_name=b'\xe7\xbd\x91\xe5\x9d\x80'),
        ),
    ]
