# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160908140001 on 2016-09-09 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20160828_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headImg',
            field=models.ImageField(upload_to='./test_upload/'),
        ),
    ]
