# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160911154422 on 2016-09-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinmeng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hk_jiaoyisuo',
            name='time_hk',
            field=models.DateTimeField(),
        ),
    ]
