# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160911154422 on 2016-09-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinmeng', '0003_auto_20160912_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='hk_jiaoyisuo',
            name='save_data',
            field=models.DateTimeField(default=1473669461.639232),
        ),
    ]
