# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160911154422 on 2016-09-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinmeng', '0004_hk_jiaoyisuo_save_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hk_jiaoyisuo',
            name='save_data',
            field=models.DateTimeField(default=1473669927.341937),
        ),
    ]
