# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160912095645 on 2016-09-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=350)),
                ('link', models.CharField(max_length=800)),
                ('data', models.DateTimeField()),
            ],
            options={
                'ordering': ['-data'],
                'db_table': 'photo',
                'indexes': [],
            },
        ),
    ]
