# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160823173927 on 2016-08-28 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20160828_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
